---
- name: Configure - Ensure datadir exists.
  file:
    path: "{{ mysql_datadir }}"
    state: directory
    owner: "{{ mysql_system_user }}"
    group: "{{ mysql_system_group }}"
    mode: 0700

- name: Configure - Ensure MySQL is configured.
  template:
    src: my.cnf.j2
    dest: "{{ mysql_config_path }}"
    owner: "{{ __mysql_root_user }}"
    group: "{{ __mysql_root_group }}"
    mode: 0644
  notify: Restart mysql

- name: Configure - Ensure MySQL is enabled on boot.
  service:
    name: "{{ mysql_service }}"
    enabled: "{{ mysql_enabled_on_startup }}"
