---
- name: Configure - Ensure datadir exists.
  file:
    path: "{{ mysql_datadir }}"
    state: directory
    owner: "{{ mysql_system_user }}"
    group: "{{ mysql_system_group }}"
    mode: 0700

- name: Configure - Ensure MySQL is started and enabled on boot.
  service:
    name: "{{ mysql_service }}"
    state: started
    enabled: yes

- name: Configure - Ensure /etc/my.cnf is configured.
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: wheel
    mode: 0644
  notify: Restart mysql
