---
- name: OpenBSD - Pre-installation.
  block:
    - name: OpenBSD - Ensure /etc/my.cnf is configured.
      template:
        src: my.cnf.j2
        dest: /etc/my.cnf
        owner: root
        group: wheel
        mode: 0644

- name: OpenBSD - Ensure MySQL python package is installed.
  openbsd_pkg:
    name: "{{ mysql_python_package }}"
    state: present

- name: OpenBSD - Ensure MySQL packages are installed.
  openbsd_pkg:
    name: "{{ mysql_packages }}"
    state: present
  register: mysql_install_packages

- name: OpenBSD - Post-installation.
  block:
    - name: OpenBSD - Ensure MySQL database is correctly initialized.
      command: /usr/local/bin/mysql_install_db

    - name: OpenBSD - Ensure /var/run/mysql has correct rights
      file:
        path: /var/run/mysql
        state: directory
        owner: "{{ mysql_system_user }}"
        group: "{{ mysql_system_group }}"
        mode: 0711

    - name: OpenBSD - Ensure MySQL is started.
      service:
        name: "{{ mysql_service }}"
        state: started

  when: mysql_install_packages.changed
