---
- name: Debian - Ensure MySQL packages are installed.
  apt:
    name: "{{ mysql_packages }}"
    state: present
  register: mysql_install_packages

- name: Debian - Post-installation.
  block:
    - name: Debian - Ensure MySQL is stopped after initial install.
      service:
        name: "{{ mysql_service }}"
        state: stopped

    - name: Debian - Ensure /etc/mysql exists.
      file:
        path: "{{ mysql_config_path | dirname }}"
        state: directory
        owner: root
        group: root

    - name: Debian - Ensure /etc/mysql/my.cnf is configured.
      template:
        src: my.cnf.j2
        dest: "{{ mysql_config_path }}"
        owner: root
        group: root
        mode: 0644

    - name: Debian - Remove /var/lib/mysql.
      file:
        path: "{{ mysql_datadir }}"
        state: absent

    - name: Debian - Recreate /var/lib/mysql.
      file:
        path: "{{ mysql_datadir }}"
        state: directory
        owner: "{{ mysql_system_user }}"
        group: "{{ mysql_system_group }}"
        mode: 0740

    - name: Debian - Ensure MySQL database is correctly initialized (mariadb).
      command: /usr/bin/mysql_install_db
      when: mysql_provider == 'mariadb'

    - name: Debian - Ensure MySQL database is correctly initialized (mysql).
      command: |
        mysqld --initialize-insecure \
               --user={{ mysql_system_user }} \
               --datadir={{ mysql_datadir }}
      when: mysql_provider == 'mysql'

    - name: Debian - Ensure /var/lib/mysql has correct rights
      file:
        path: /var/lib/mysql
        state: directory
        recurse: yes
        owner: "{{ mysql_system_user }}"
        group: "{{ mysql_system_group }}"

  when: mysql_install_packages.changed
