---
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Ensure role's variable are correctly configured.
  assert:
    that:
      - "__mysql_db_admin_password is defined"
      - "mysql_provider in __mysql_providers"

- name: Execute OS-specific tasks.
  include_tasks: install-{{ ansible_distribution }}.yml

- include_tasks: configure.yml
- include_tasks: password-change.yml
  when: mysql_install_packages.changed or mysql_db_admin_password_update
- include_tasks: secure-installation.yml
  when: mysql_install_packages.changed
- include_tasks: databases.yml
- include_tasks: users.yml
